package life.majiang.community.entity;

public class NtificationEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.notifier
     *
     * @mbggenerated
     */
    private Long notifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.reciver
     *
     * @mbggenerated
     */
    private Long reciver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.outerId
     *
     * @mbggenerated
     */
    private Long outerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.gmt_create
     *
     * @mbggenerated
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.notifier_name
     *
     * @mbggenerated
     */
    private String notifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ntification.outer_title
     *
     * @mbggenerated
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.id
     *
     * @return the value of ntification.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.id
     *
     * @param id the value for ntification.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.notifier
     *
     * @return the value of ntification.notifier
     *
     * @mbggenerated
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.notifier
     *
     * @param notifier the value for ntification.notifier
     *
     * @mbggenerated
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.reciver
     *
     * @return the value of ntification.reciver
     *
     * @mbggenerated
     * @param aLong
     */
    public Long getReciver() {
        return reciver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.reciver
     *
     * @param reciver the value for ntification.reciver
     *
     * @mbggenerated
     */
    public void setReciver(Long reciver) {
        this.reciver = reciver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.outerId
     *
     * @return the value of ntification.outerId
     *
     * @mbggenerated
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.outerId
     *
     * @param outerid the value for ntification.outerId
     *
     * @mbggenerated
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.type
     *
     * @return the value of ntification.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.type
     *
     * @param type the value for ntification.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.gmt_create
     *
     * @return the value of ntification.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.gmt_create
     *
     * @param gmtCreate the value for ntification.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.status
     *
     * @return the value of ntification.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.status
     *
     * @param status the value for ntification.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.notifier_name
     *
     * @return the value of ntification.notifier_name
     *
     * @mbggenerated
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.notifier_name
     *
     * @param notifierName the value for ntification.notifier_name
     *
     * @mbggenerated
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ntification.outer_title
     *
     * @return the value of ntification.outer_title
     *
     * @mbggenerated
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ntification.outer_title
     *
     * @param outerTitle the value for ntification.outer_title
     *
     * @mbggenerated
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }


}